#Copyright 2022-2023 Hewlett Packard Enterprise Development LP
version: 2.1
orbs:
  slack: circleci/slack@4.12.5

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

# for AWS creds to download image
common-context: &common-context
  context: ecr-6644

attach: &attach
  attach_workspace:
    at: ~/project

jobs:
  print-a-message:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run: echo "hello"